#blog-postgres-credentials.yml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  db-name: YmxvZ2FwcGRiX3Byb2R1Y3Rpb24=
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
  master-key: ZjQwOWYyYWIzNzMzN2E3NmY1YTI0MmVmZTM3Nzk3ZmM=
