apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-pipeline-run
spec:
  pipelineRef:
    name: build-and-push-pipeline
  serviceAccountName: default
  resources:
    - name: git-source
      resourceSpec:
        type: git
        params:
          - name: url
            value: "https://github.com/praks7v/DevOps-Assesment.git"
  params:
    - name: gitrepo
      value:
        url: "https://github.com/praks7v/DevOps-Assesment.git"
    - name: context-dir
      value: "."
    - name: dockerfile
      value: "./Dockerfile"
    - name: docker-image
      value: "https://hub.docker.com/r/praks007/blog-web:v1"
  secrets:
    - name: regcred
